from pydantic import BaseModel, Field

from enum import Enum

class Intent(str, Enum):
    POLICY_LOOKUP = "policy_lookup"
    PROCEDURE_LOOKUP = "procedure_lookup"
    COMPARISON = "comparison"
    FAQ = "faq"
    GENERAL = "general"

class PlannerOutput(BaseModel):
    """
    Structured output produced by the Planner Agent.
    """

    intent: Intent = Field(
        description="The user's intent."
    )

    rewritten_query: str = Field(
        description="Optimized query for retrieval."
    )

    requires_decomposition: bool = Field(
        description="Whether the query should be split into sub-queries."
    )

    sub_queries: list[str] = Field(
        default_factory=list,
        description="Sub-queries generated by the planner."
    )

    metadata_filters: dict[str, str] | None = Field(
        default=None,
        description="Metadata filters for retrieval."
    )

    top_k: int = Field(
        default=5,
        description="Number of chunks to retrieve."
    )